// <auto-generated />
namespace CringeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeduserpassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeduserpassword));
        
        string IMigrationMetadata.Id
        {
            get { return "202105062004478_changed-user-password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
