// <auto-generated />
namespace CringeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class conferencesdroppedparticipationId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conferencesdroppedparticipationId));
        
        string IMigrationMetadata.Id
        {
            get { return "202105042104591_conferences-dropped-participationId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
